[19-04-52] [ENTRY]: [Nathan]
[19-04-52] [SYSTEM_IO]: System data pared in IOUtil's static block
[19-04-52] [SYSTEM_IO]: Suggestions pared in IOUtil's static block
[19-04-52] [SYSTEM_IO]: Exit conditions pared in IOUtil's static block
[19-04-52] [SYSTEM_IO]: DebugHashes pared in IOUtil's static block
[19-04-54] [LOGIN]: [AUTOCYPHER ATTEMPT]
[19-04-54] [JAVA ARGS]: [LOCATION] [La casa de Nathan]
[19-04-54] [LOGIN]: [AUTOCYPHER PASS, e5a50641-21d1-3654-b738-c0e4b2dc61b1]
[19-04-54] [SYSTEM_IO]: Userdata requested: Name
[19-04-54] [SYSTEM_IO]: Userdata requested: RandomBackground
[19-04-54] [SYSTEM_IO]: Userdata requested: FullScreen
[19-04-54] [SYSTEM_IO]: Userdata requested: Name
[19-04-54] [SYSTEM_IO]: Userdata requested: Foreground
[19-04-54] [SYSTEM_IO]: Userdata requested: Foreground
[19-04-54] [SYSTEM_IO]: Userdata requested: FullScreen
[19-04-54] [SYSTEM_IO]: Userdata requested: FullScreen
[19-04-54] [SYSTEM_IO]: Userdata requested: Foreground
[19-04-54] [SYSTEM_IO]: Userdata requested: Font
[19-04-54] [SYSTEM_IO]: Userdata requested: OutputBorder
[19-04-54] [SYSTEM_IO]: Userdata requested: FullScreen
[19-04-54] [SYSTEM_IO]: Userdata requested: InputBorder
[19-04-54] [SYSTEM_IO]: Userdata requested: Foreground
[19-04-54] [SYSTEM_IO]: Userdata requested: Foreground
[19-04-54] [SYSTEM_IO]: Userdata requested: Foreground
[19-04-54] [SYSTEM_IO]: Userdata requested: Font
[19-04-54] [SYSTEM_IO]: Userdata requested: OutputFill
[19-04-54] [SYSTEM_IO]: Userdata requested: InputFill
[19-04-55] [ACTION]: CyderFrame disposed with fastclose: true, CyderFrame: Component name = [cyder.ui.CyderFrame], bounds = [(980, 396, 600, 600)], hash = [364090757], parentFrame = [Object itself is the top level frame], associated text = [No getText() method found], tooltip text = [No getTooltipText() method found], title = [Cyder Splash]
[19-04-55] [ACTION]: Console loaded in 3287ms
[19-04-55] [SYSTEM_IO]: Userdata requested: DebugWindows
[19-04-55] [ENTRY]: [TESTING MODE]
[19-04-55] [SYSTEM_IO]: Userdata requested: laststart
[19-04-55] [SYSTEM_IO]: Userdata requested: IntroMusic
[19-04-55] [ACTION]: [Stellar Cyder [Nathan]] [NOTIFICATION] Console loaded in 3287ms
[19-04-55] [SYSTEM_IO]: Userdata requested: persistentnotifications
[19-04-57] [CLIENT]: git
[19-04-57] [SYSTEM_IO]: Userdata requested: filterchat
[19-04-57] [HANDLE]: GENERAL COMMAND HANDLED
[19-04-57] [HANDLE]: PRIMARY HANDLE
[19-04-58] [CONSOLE_OUT]: [STRING] Validating github link: asdf
[19-04-58] [CONSOLE_OUT]: [STRING] Provided repo link is invalid
[19-04-59] [CONSOLE_OUT]: [STRING] Clone failed
[19-05-37] [CLIENT]: git
[19-05-37] [SYSTEM_IO]: Userdata requested: filterchat
[19-05-37] [HANDLE]: GENERAL COMMAND HANDLED
[19-05-37] [HANDLE]: PRIMARY HANDLE
[19-05-37] [EXCEPTION]: 
Exception origin: java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2104)
From line: 2104
Trace: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@74335a36 rejected from java.util.concurrent.ThreadPoolExecutor@700cd068[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1397)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:686)
	at cyder.utilities.GitHubUtil.cloneRepoToDirectory(GitHubUtil.java:166)
	at cyder.handlers.internal.InputHandler.lambda$generalCommandCheck$9(InputHandler.java:1228)
	at java.base/java.lang.Thread.run(Thread.java:844)
[19-05-37] [SYSTEM_IO]: Userdata requested: SilenceErrors
[19-05-37] [DEBUG]: 
Exception origin: java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2104)
From line: 2104
Trace: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@74335a36 rejected from java.util.concurrent.ThreadPoolExecutor@700cd068[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1397)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:686)
	at cyder.utilities.GitHubUtil.cloneRepoToDirectory(GitHubUtil.java:166)
	at cyder.handlers.internal.InputHandler.lambda$generalCommandCheck$9(InputHandler.java:1228)
	at java.base/java.lang.Thread.run(Thread.java:844)
[19-06-16] [CLIENT]: clear
[19-06-16] [SYSTEM_IO]: Userdata requested: filterchat
[19-06-16] [HANDLE]: GENERAL COMMAND HANDLED
[19-06-16] [HANDLE]: PRIMARY HANDLE
[19-06-18] [CLIENT]: git
[19-06-18] [SYSTEM_IO]: Userdata requested: filterchat
[19-06-18] [HANDLE]: GENERAL COMMAND HANDLED
[19-06-18] [HANDLE]: PRIMARY HANDLE
[19-06-18] [EXCEPTION]: 
Exception origin: java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2104)
From line: 2104
Trace: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@485ad201 rejected from java.util.concurrent.ThreadPoolExecutor@700cd068[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1397)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:686)
	at cyder.utilities.GitHubUtil.cloneRepoToDirectory(GitHubUtil.java:166)
	at cyder.handlers.internal.InputHandler.lambda$generalCommandCheck$9(InputHandler.java:1228)
	at java.base/java.lang.Thread.run(Thread.java:844)
[19-06-18] [SYSTEM_IO]: Userdata requested: SilenceErrors
[19-06-18] [DEBUG]: 
Exception origin: java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2104)
From line: 2104
Trace: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@485ad201 rejected from java.util.concurrent.ThreadPoolExecutor@700cd068[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1397)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:686)
	at cyder.utilities.GitHubUtil.cloneRepoToDirectory(GitHubUtil.java:166)
	at cyder.handlers.internal.InputHandler.lambda$generalCommandCheck$9(InputHandler.java:1228)
	at java.base/java.lang.Thread.run(Thread.java:844)
[19-06-23] [CLIENT]: git
[19-06-23] [SYSTEM_IO]: Userdata requested: filterchat
[19-06-23] [HANDLE]: GENERAL COMMAND HANDLED
[19-06-23] [HANDLE]: PRIMARY HANDLE
[19-06-23] [EXCEPTION]: 
Exception origin: java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2104)
From line: 2104
Trace: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@39d1437d rejected from java.util.concurrent.ThreadPoolExecutor@700cd068[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1397)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:686)
	at cyder.utilities.GitHubUtil.cloneRepoToDirectory(GitHubUtil.java:166)
	at cyder.handlers.internal.InputHandler.lambda$generalCommandCheck$9(InputHandler.java:1228)
	at java.base/java.lang.Thread.run(Thread.java:844)
[19-06-23] [SYSTEM_IO]: Userdata requested: SilenceErrors
[19-06-23] [DEBUG]: 
Exception origin: java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2104)
From line: 2104
Trace: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@39d1437d rejected from java.util.concurrent.ThreadPoolExecutor@700cd068[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1397)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:686)
	at cyder.utilities.GitHubUtil.cloneRepoToDirectory(GitHubUtil.java:166)
	at cyder.handlers.internal.InputHandler.lambda$generalCommandCheck$9(InputHandler.java:1228)
	at java.base/java.lang.Thread.run(Thread.java:844)
[19-07-53] [EOL]: Log completed, Cyder was force closed by an external entity: exit code: -200 [External Stop], exceptions thrown: 3