[17-56-29] [ENTRY]: [Nathan]
[17-56-29] [THREAD STARTED]: Singular Cyder Instance Ensurer
[17-56-30] [THREAD STARTED]: Splash Loader
[17-56-30] [SYSTEM_IO]: Unable to create all userfiles for user [7d7ebb00-81fe-329f-8a78-62f463d0b7da] after 1000 attempts [4x]
[17-56-30] [THREAD STARTED]: Splash Animation
[17-56-30] [SYSTEM_IO]: Created temperatory file: 17-56-30.stacktrace
[17-56-30] [EXCEPTION]:
Exception origin: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
From line: -2
Trace: java.lang.IllegalArgumentException: wrong number of arguments
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:471)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:562)
at cyder.genesis.Cyder.main(Cyder.java:96)
[17-56-30] [SYSTEM_IO]: File already existed in userspace: 17-56-30.stacktrace
[17-56-30] [EXCEPTION]:
Exception origin: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
From line: -2
Trace: java.lang.IllegalArgumentException: wrong number of arguments
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:471)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:562)
at cyder.genesis.Cyder.main(Cyder.java:96)
[17-56-30] [SYSTEM_IO]: File already existed in userspace: 17-56-30.stacktrace
[17-56-30] [EXCEPTION]:
Exception origin: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
From line: -2
Trace: java.lang.IllegalArgumentException: wrong number of arguments
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:471)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:562)
at cyder.genesis.Cyder.main(Cyder.java:96)
[17-56-30] [SYSTEM_IO]: File already existed in userspace: 17-56-30.stacktrace
[17-56-30] [EXCEPTION]:
Exception origin: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
From line: -2
Trace: java.lang.IllegalArgumentException: wrong number of arguments
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:471)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:562)
at cyder.genesis.Cyder.main(Cyder.java:96)
[17-56-30] [SYSTEM_IO]: File already existed in userspace: 17-56-30.stacktrace
[17-56-30] [EXCEPTION]:
Exception origin: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
From line: -2
Trace: java.lang.IllegalArgumentException: wrong number of arguments
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:471)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:562)
at cyder.genesis.Cyder.main(Cyder.java:96)
[17-56-30] [SYSTEM_IO]: File already existed in userspace: 17-56-30.stacktrace
[17-56-30] [EXCEPTION]:
Exception origin: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
From line: -2
Trace: java.lang.IllegalArgumentException: wrong number of arguments
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:471)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:562)
at cyder.genesis.Cyder.main(Cyder.java:96)
[17-56-30] [SYSTEM_IO]: File already existed in userspace: 17-56-30.stacktrace
[17-56-30] [EXCEPTION]:
Exception origin: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
From line: -2
Trace: java.lang.IllegalArgumentException: wrong number of arguments
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:471)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:562)
at cyder.genesis.Cyder.main(Cyder.java:96)
[17-56-30] [SYSTEM_IO]: File already existed in userspace: 17-56-30.stacktrace
[17-56-30] [EXCEPTION]:
Exception origin: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
From line: -2
Trace: java.lang.IllegalArgumentException: wrong number of arguments
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:471)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:562)
at cyder.genesis.Cyder.main(Cyder.java:96)
[17-56-30] [SYSTEM_IO]: File already existed in userspace: 17-56-30.stacktrace
[17-56-30] [EXCEPTION]:
Exception origin: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
From line: -2
Trace: java.lang.IllegalArgumentException: wrong number of arguments
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:471)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:562)
at cyder.genesis.Cyder.main(Cyder.java:96)
[17-56-30] [SYSTEM_IO]: File already existed in userspace: 17-56-30.stacktrace
[17-56-30] [EXCEPTION]:
Exception origin: java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
From line: -2
Trace: java.lang.IllegalArgumentException: wrong number of arguments
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:471)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:562)
at cyder.genesis.Cyder.main(Cyder.java:96)
[17-56-30] [CORRUPTION]: [BACKUP SUCCESS] Successfully restored 7d7ebb00-81fe-329f-8a78-62f463d0b7da from: 7d7ebb00-81fe-329f-8a78-62f463d0b7da_1646787699135
[17-56-31] [THREAD STARTED]: Cyder Start Secondary Subroutines
[17-56-31] [LOGIN]: [AUTOCYPHER ATTEMPT]
[17-56-31] [THREAD STARTED]: JVM Logger
[17-56-31] [ACTION]: Requested deletion of: C:\Users\Nathan\Documents\IntelliJava\Cyder\dynamic\tmp
[17-56-31] [LOGIN]: [[AUTOCYPHER PASS]: 7d7ebb00-81fe-329f-8a78-62f463d0b7da]
[17-56-31] [SYSTEM_IO]: Userdata requested: RandomBackground
[17-56-31] [SYSTEM_IO]: Created temperatory file: 17-56-31.stacktrace
[17-56-31] [EXCEPTION]:
Exception origin: cyder.utilities.ColorUtil.hexToRgb(ColorUtil.java:31)
From line: 31
Trace: java.lang.NullPointerException
at cyder.utilities.ColorUtil.hexToRgb(ColorUtil.java:31)
at cyder.ui.ConsoleFrame.launch(ConsoleFrame.java:272)
at cyder.handlers.internal.LoginHandler.recognize(LoginHandler.java:513)
at cyder.handlers.internal.LoginHandler.autoCypher(LoginHandler.java:553)
at cyder.handlers.internal.LoginHandler.determineCyderEntry(LoginHandler.java:447)
at cyder.genesis.Cyder.main(Cyder.java:119)
[17-56-31] [SYSTEM_IO]: Userdata requested: SilenceErrors
[17-57-21] [ACTION]: CyderFrame disposed with fastclose: true, CyderFrame: Component name = [cyder.ui.CyderFrame], bounds = [(980, 396, 600, 600)], hash = [1742880767], parentFrame = [Object itself is the top level frame], associated text = [No getText() method found], tooltip text = [No getTooltipText() method found], title = [Cyder Splash]
[17-57-21] [THREAD STARTED]: Cyder Splash CyderFrame dispose thread
[17-57-23] [ACTION]: Component name = [cyder.ui.DragLabel], bounds = [(2, 2, 391, 28)], hash = [-14688418], parentFrame = [Startup Exception], associated text = [No getText() method found], tooltip text = [No getTooltipText() method found], title = [No getTitle() method found]
[17-57-23] [ACTION]: CyderFrame disposed with fastclose: false, CyderFrame: Component name = [cyder.ui.CyderFrame], bounds = [(1083, 646, 395, 100)], hash = [262607617], parentFrame = [Object itself is the top level frame], associated text = [No getText() method found], tooltip text = [No getTooltipText() method found], title = [Startup Exception]
[17-57-23] [THREAD STARTED]: Startup Exception CyderFrame dispose thread
[17-57-23] [SYSTEM_IO]: Userdata requested: closeanimation
[17-57-23] [EXIT]: [RUNTIME] 54s
[17-57-23] [EOL]: Log completed, exiting Cyder with exit code: -7 [Fatal Timeout], exceptions thrown: 11
