[18-02-09] [ENTRY]: [Nathan]
[18-02-09] [THREAD STARTED]: Singular Cyder Instance Ensurer
[18-02-10] [THREAD STARTED]: Splash Loader
[18-02-10] [SYSTEM_IO]: Unable to create all userfiles for user [7d7ebb00-81fe-329f-8a78-62f463d0b7da] after 1000 attempts [4x]
[18-02-10] [SYSTEM_IO]: Created temperatory file: 18-02-10.stacktrace
[18-02-10] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:486)
From line: 486
Trace: java.lang.NullPointerException
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:486)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:564)
at cyder.genesis.Cyder.main(Cyder.java:96)
[18-02-10] [SYSTEM_IO]: File already existed in userspace: 18-02-10.stacktrace
[18-02-10] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:486)
From line: 486
Trace: java.lang.NullPointerException
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:486)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:564)
at cyder.genesis.Cyder.main(Cyder.java:96)
[18-02-10] [SYSTEM_IO]: File already existed in userspace: 18-02-10.stacktrace
[18-02-10] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:486)
From line: 486
Trace: java.lang.NullPointerException
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:486)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:564)
at cyder.genesis.Cyder.main(Cyder.java:96)
[18-02-10] [SYSTEM_IO]: File already existed in userspace: 18-02-10.stacktrace
[18-02-10] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:486)
From line: 486
Trace: java.lang.NullPointerException
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:486)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:564)
at cyder.genesis.Cyder.main(Cyder.java:96)
[18-02-10] [SYSTEM_IO]: File already existed in userspace: 18-02-10.stacktrace
[18-02-10] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:486)
From line: 486
Trace: java.lang.NullPointerException
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:486)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:564)
at cyder.genesis.Cyder.main(Cyder.java:96)
[18-02-10] [SYSTEM_IO]: File already existed in userspace: 18-02-10.stacktrace
[18-02-10] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:486)
From line: 486
Trace: java.lang.NullPointerException
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:486)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:564)
at cyder.genesis.Cyder.main(Cyder.java:96)
[18-02-10] [SYSTEM_IO]: File already existed in userspace: 18-02-10.stacktrace
[18-02-10] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:486)
From line: 486
Trace: java.lang.NullPointerException
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:486)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:564)
at cyder.genesis.Cyder.main(Cyder.java:96)
[18-02-10] [SYSTEM_IO]: File already existed in userspace: 18-02-10.stacktrace
[18-02-10] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:486)
From line: 486
Trace: java.lang.NullPointerException
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:486)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:564)
at cyder.genesis.Cyder.main(Cyder.java:96)
[18-02-10] [SYSTEM_IO]: File already existed in userspace: 18-02-10.stacktrace
[18-02-10] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:486)
From line: 486
Trace: java.lang.NullPointerException
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:486)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:564)
at cyder.genesis.Cyder.main(Cyder.java:96)
[18-02-10] [SYSTEM_IO]: File already existed in userspace: 18-02-10.stacktrace
[18-02-10] [THREAD STARTED]: Splash Animation
[18-02-10] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:486)
From line: 486
Trace: java.lang.NullPointerException
at cyder.utilities.UserUtil.getterSetterValidator(UserUtil.java:486)
at cyder.utilities.UserUtil.validateAllusers(UserUtil.java:564)
at cyder.genesis.Cyder.main(Cyder.java:96)
[18-02-10] [CORRUPTION]: [BACKUP SUCCESS] Successfully restored 7d7ebb00-81fe-329f-8a78-62f463d0b7da from: 7d7ebb00-81fe-329f-8a78-62f463d0b7da_1646787699135
[18-02-11] [THREAD STARTED]: Cyder Start Secondary Subroutines
[18-02-11] [LOGIN]: [AUTOCYPHER ATTEMPT]
[18-02-11] [THREAD STARTED]: JVM Logger
[18-02-11] [ACTION]: Requested deletion of: C:\Users\Nathan\Documents\IntelliJava\Cyder\dynamic\tmp
[18-02-11] [LOGIN]: [[AUTOCYPHER PASS]: 7d7ebb00-81fe-329f-8a78-62f463d0b7da]
[18-02-11] [SYSTEM_IO]: Userdata requested: RandomBackground
[18-02-11] [SYSTEM_IO]: Created temperatory file: 18-02-11.stacktrace
[18-02-11] [EXCEPTION]:
Exception origin: cyder.utilities.ColorUtil.hexToRgb(ColorUtil.java:31)
From line: 31
Trace: java.lang.NullPointerException
at cyder.utilities.ColorUtil.hexToRgb(ColorUtil.java:31)
at cyder.ui.ConsoleFrame.launch(ConsoleFrame.java:272)
at cyder.handlers.internal.LoginHandler.recognize(LoginHandler.java:513)
at cyder.handlers.internal.LoginHandler.autoCypher(LoginHandler.java:553)
at cyder.handlers.internal.LoginHandler.determineCyderEntry(LoginHandler.java:447)
at cyder.genesis.Cyder.main(Cyder.java:119)
[18-02-11] [SYSTEM_IO]: Userdata requested: SilenceErrors
[18-03-02] [ACTION]: CyderFrame disposed with fastclose: true, CyderFrame: Component name = [cyder.ui.CyderFrame], bounds = [(980, 396, 600, 600)], hash = [1909277369], parentFrame = [Object itself is the top level frame], associated text = [No getText() method found], tooltip text = [No getTooltipText() method found], title = [Cyder Splash]
[18-03-02] [THREAD STARTED]: Cyder Splash CyderFrame dispose thread
[18-03-19] [ACTION]: Component name = [cyder.ui.DragLabel], bounds = [(2, 2, 391, 28)], hash = [-14688418], parentFrame = [Startup Exception], associated text = [No getText() method found], tooltip text = [No getTooltipText() method found], title = [No getTitle() method found]
[18-03-19] [ACTION]: CyderFrame disposed with fastclose: false, CyderFrame: Component name = [cyder.ui.CyderFrame], bounds = [(1083, 646, 395, 100)], hash = [138931282], parentFrame = [Object itself is the top level frame], associated text = [No getText() method found], tooltip text = [No getTooltipText() method found], title = [Startup Exception]
[18-03-19] [THREAD STARTED]: Startup Exception CyderFrame dispose thread
[18-03-19] [SYSTEM_IO]: Userdata requested: closeanimation
[18-03-19] [EXIT]: [RUNTIME] 1m 9s
[18-03-19] [EOL]: Log completed, exiting Cyder with exit code: -7 [Fatal Timeout], exceptions thrown: 11
