[18-29-28] [ENTRY]: [Nathan]
[18-29-28] [THREAD STARTED]: Singular Cyder Instance Ensurer
[18-29-28] [SYSTEM_IO]: Created temperatory file: 18-29-28.stacktrace
[18-29-28] [EXCEPTION]:
Exception origin: java.base/java.net.DualStackPlainSocketImpl.bind0(Native Method)
From line: -2
Trace: java.net.BindException: Address already in use: NET_Bind
at java.base/java.net.DualStackPlainSocketImpl.bind0(Native Method)
at java.base/java.net.DualStackPlainSocketImpl.socketBind(DualStackPlainSocketImpl.java:106)
at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:437)
at java.base/java.net.PlainSocketImpl.bind(PlainSocketImpl.java:174)
at java.base/java.net.ServerSocket.bind(ServerSocket.java:381)
at java.base/java.net.ServerSocket.<init>(ServerSocket.java:243)
at java.base/java.net.ServerSocket.<init>(ServerSocket.java:135)
at cyder.genesis.Cyder.lambda$ensureCyderSingleInstance$2(Cyder.java:206)
at java.base/java.lang.Thread.run(Thread.java:844)
[18-29-29] [ACTION]: Requested deletion of: C:\Users\Nathan\Documents\IntelliJava\Cyder\dynamic\tmp
[18-29-57] [EOL]: Log completed, Cyder crashed unexpectedly: exit code: -9 External Stop, exceptions thrown: 1
